version: '3.8'

services:
  front:
    platform: linux/x86_64
    restart: always
    build: ./front
    ports:
      - "8081:5173"
    env_file:
      - ./front.env
    command: "npm run dev -- --host"
    volumes:
      - ./front/src:/app/src
  back:
    build: ./back
    ports:
      - "3000:3000"
    env_file:
      - ./back.env
    command: "npm run start:dev"
    volumes:
      - ./back/src:/app/src

  postgres_database:
    container_name: postgres_database
    image: postgres:latest
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - "5434:5434"

  adminer:
    container_name: adminer_destiny
    image: adminer:latest
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - ./adminer.env
    depends_on:
      - postgres_database

