version: '3.8'

services:
  front:
    platform: linux/x86_64
    restart: always
    build: ./front
    ports:
      - "8081:5173"
    env_file:
      - ./front.env
    command: "npm run dev -- --host"
    volumes:
      - ./front/src:/app/src
  back:
    build: ./back
    ports:
      - "3000:3000"
    env_file:
      - ./back.env
    command: "npm run start:dev"
    volumes:
      - ./back/src:/app/src

  
  postgres_database:
    container_name: postgres_database
    image: postgres:latest
    restart: always
    volumes: 
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5434:5432"

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8082:8080"
    
    environment:
    - ADMINER_DEFAULT_SERVER=postgres_database
    - ADMINER_DEFAULT_USERNAME=useradmin
    - ADMINER_DEFAULT_PASSWORD=password
    depends_on:
      - postgres_database

volumes:
  dbdata: