version: '3.8'

services:
  front:
    platform: linux/x86_64
    restart: always
    build: .
    ports:
      - "8081:5173"
    env_file:
      - ./front.env
    command: "npm run dev -- --host"
    volumes:
      - ./front/src:/app/src